format = """
[](bg:#D3E4FF)\
$charater\
[](bg:#3B4252)\
$directory\
[](fg:#3B4252) \
$git_branch\
$git_status\
[](fg:#4C566A) \
$c\
$golang\
$java\
$lua\
$nodejs\
$python\
$rust\
[](fg:#6789A8)\
$docker_context\
[î‚°](fg:#06969A bg:#33658A)\
$cmd_duration\
[î‚° ](fg:#33658A)
"""
command_timeout = 5000
# Disable the blank line at the start of the prompt
# add_newline = false
[line_break]
disabled = false

[directory]
read_only = " ï ½"
style = "bg:#3B4252 fg:#CDDFFF"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "â€¦/"
truncate_to_repo = true # truncates directory to root folder if in github repo

[directory.substitutions]
"Documents" = "ïœ˜ "
"Downloads" = "ï€™ "
"Music" = "ï€ "
"Pictures" = "ï€¾ "

[character]
success_symbol = "[ó°¸](bold green)"
error_symbol = "[âœ—](bold red)"
style = "bg:#1d2021"
format = '[ $symbol ]($style)'

[cmd_duration]
min_time = 4
show_milliseconds = false
disabled = false
style = "bg:#33658A italic yellow"
format = '[ took $duration ]($style)'

[c]
symbol = "î˜ "
style = "bg:#6789A8"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = "ïŒˆ "
style = "bg:#06969A"
format = '[ $symbol $context ]($style) $path'

[elixir]
symbol = "î‰µ "
style = "bg:#6789A8"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = "î˜¬ "
style = "bg:#6789A8"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = "ï„“"
style = "bg:#4C566A"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#4C566A"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = "î˜§ "
style = "bg:#6789A8"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = "î· "
style = "bg:#6789A8"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = "î‰– "
style = "bg:#6789A8"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = "î˜¤ "
style = "bg:#6789A8"
format = '[ $symbol ($version) ]($style)'

[lua]
symbol = "ğŸŒ™ "
style = "bg:#6789A8"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = "îœ˜"
style = "bg:#6789A8"
format = '[ $symbol ($version) ]($style)'

[python]
symbol = "ğŸ "
style = "bg:#6789A8"
format = '[ ${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'

[rust]
symbol = "î¨"
style = "bg:#6789A8"
format = '[ $symbol ($version) ]($style)'

